version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # Create your database
      MYSQL_DATABASE: dalandadb
      # Allow the root user to have an empty password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: karimkli/my-spring-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL:      jdbc:mysql://db:3306/dalandadb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db_data:
